#!/bin/bash
#
#       /etc/rc.d/init.d/<servicename>
#
#       <description of the *service*>
#       <any general comments about this init script>
#
# <tags -- see below for tag definitions.  *Every line* from the top
#  of the file to the end of the tags section must begin with a #
#  character.  After the tags section, there should be a blank line.
#  This keeps normal comments in the rest of the file from being
#  mistaken for tags, should they happen to fit the pattern.>

#
# To unable this service you can use
# chkconfig --add <servicename>
#

# Source function library.
. /etc/init.d/functions

NAME=container
VERSION=version
CONTAINER=$NAME:$VERSION
CONTAINER_OPTS="-p 80:8080"

start() {
        echo -n "Starting $CONTAINER as $NAME: "
        /usr/bin/docker rm $NAME 2>/dev/null
        /usr/bin/docker run --name=$NAME -d $CONTAINER_OPTS 
        RETVAL=$?
        touch /var/lock/subsys/$NAME
        return $RETVAL
}

stop() {
        echo -n "Shutting down $NAME: "
        /usr/bin/docker kill $NAME
        RETVAL=$?
        rm -f /var/lock/subsys/$NAME
        return $RETVAL
}

status() {
        echo -n "Checking $NAME status: "
        /usr/bin/docker top $NAME 
        RETVAL=$?
        return $RETVAL
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status
        ;;
    restart)
        stop
        start
        ;;
    reload)
        stop
        start
        ;;
    *)
        echo "Usage: $0 {start|stop|status|reload|restart[|probe]"
        exit 1
        ;;
esac
exit $?

