#!/bin/bash
#
#       /etc/rc.d/init.d/<servicename>
#
#       <description of the *service*>
#       <any general comments about this init script>
#
# chkconfig:   2345 95 95
# description: <description of the service>

#
# To unable this service you can use
# chkconfig --add <servicename>
#

# Source function library.
. /etc/init.d/functions

NAME=container
VERSION=version
CONTAINER=$NAME:$VERSION
CONTAINER_OPTS="-p 80:8080 -v /srv/toto:/srv/toto -e VAR=value"

start() {
        echo -n "Starting $CONTAINER: "
        /usr/bin/docker rm $NAME
        /usr/bin/docker run --name=$NAME -d $CONTAINER_OPTS $CONTAINER > /dev/null
        RETVAL=$?
        touch /var/lock/subsys/$NAME
        return $RETVAL
}

stop() {
        echo -n "Shutting down $CONTAINER: "
        /usr/bin/docker kill $NAME
        RETVAL=$?
        rm -f /var/lock/subsys/$NAME
        return $RETVAL
}

status() {
        echo -n "Checking $NAME status: "
        /usr/bin/docker top $NAME >/dev/null 2>&1
        RETVAL=$?
        [ $RETVAL -eq 0 ] && echo "running" || echo "stoped"
        return $RETVAL
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status
        ;;
    restart)
        stop
        start
        ;;
    reload)
        stop
        start
        ;;
    *)
        echo "Usage: $0 {start|stop|status|reload|restart[|probe]"
        exit 1
        ;;
esac
exit $?

